### PR TITLE
implement fallback portal

### PR DESCRIPTION
**Pull request by brucewpaul**
the point of this pr is to create a fallback protal that uses the
custom portal if we are not on react16 (by checking to see if
ReactDOM.createPortal is present), and the new Portal if we are on
React16.

this pr addresses https://github.com/tajo/react-portal/issues/180

@majapw @lencioni @tajo @ranneyd @ljharb

### CODE REVIEW

**Comment by tajo** [comment]
This is not a way how to do it. You would get completely different `<Portal />` component for:

```js
import { Portal } from 'react-portal';
```

with React15 and React16.

LegacyPortal should be stripped down to bare minimum, so it can match API of V4 `<Portal />`. `<PortalWithState />` should be able to use it without further changes. The V3 API has no place (future) in the current version.

Also, we need to set up tests for multiple React versions.

File: package.json [hunk 1]
```diff
@@ -27,7 +27,8 @@
     "prepublish": "cross-env NODE_ENV=production npm run build",
     "lint": "eslint webpack.config.js src/**/*.js",
     "format": "prettier --write \"**/*.js\"",
-    "test": "cross-env BABEL_ENV=commonjs jest --no-cache"
+    "test": "cross-env BABEL_ENV=commonjs jest --no-cache",
+    "react": "enzyme-adapter-react-install 16.2.0"
```
Comment (brucewpaul) [inline package.json]: there is a bug in semver.intersect that enzyme-adapter-react-helper uses. Once that is resolved, we will be able to use a wider semver as opposed to locking it down a specific version

**Comment by brucewpaul** [comment]
@tajo ptal

cleaned it up a little bit, added `enzyme-adapter-react-helper` and tests for both versions, and stripped down LegacyPortal

**Comment by brucewpaul** [comment]
and @ranneyd you said you wanted to work on this as well if you wanted to take a look

File: __tests__/Portal.js [hunk 2]
```diff
@@ -1,27 +1,72 @@
...
+      '<div id="root"><!-- react-empty: 1 --></div>'
+    );
+    expect(document.body.lastChild.outerHTML).toBe(
+      '<div><div data-reactroot="">Foo</div></div>'
+    );
+  }
+);
+
+ifReact('>= 16', test, test.skip)(
+  'should append portal to the document.body',
```
Comment (tajo) [inline __tests__/Portal.js]: > should append portal to a custom node

File: __tests__/Portal.js [hunk 3]
```diff
@@ -1,27 +1,72 @@
...
+    );
+    expect(document.body.firstChild.outerHTML).toBe('<div id="root"></div>');
+    expect(document.getElementById('custom').outerHTML).toBe(
+      '<div id="custom">Foo</div>'
+    );
+  }
+);
+
+ifReact('< 16', test, test.skip)(
+  'should append portal to the document.body',
```
Comment (tajo) [inline __tests__/Portal.js]: custom element

File: src/PortalWithState.js [hunk 4]
```diff
@@ -1,7 +1,7 @@
 import React from 'react';
 import { findDOMNode } from 'react-dom';
 import PropTypes from 'prop-types';
-import Portal from './Portal';
+import Portal from './PortalUtil';
```
Comment (tajo) [inline src/PortalWithState.js]: Can we rename `PortalUtil` to `PortalCompat`. Or anyone else having a better idea?

Comment (brucewpaul) [reply src/PortalWithState.js]: 👍 `PortalCompat` seems like a much better name, let's go with that unless someone else comes up with a better one

**Comment by tajo** [comment]
Thanks. Looks good to me! I'll do some more testing later this week. Feedback from others would be great too.

**Comment by brucewpaul** [comment]
awesome thanks! It would be good to get some good testing in with react15, as this was my first time looking at the source code of react-portals. I will try to do some testing as well and have some of my team members take a look at it as well (cc @majapw @lencioni @ljharb).

This is currently causing a problem for us at Airbnb and would be great to get this out as soon as possible, so please let me know if there is anything else that would be helpful in terms of getting this out.

File: src/LegacyPortal.js [hunk 5]
```diff
@@ -0,0 +1,62 @@
+import React from 'react';
+import ReactDOM, { findDOMNode } from 'react-dom';
+import PropTypes from 'prop-types';
+
+const KEYCODES = {
```
Comment (lencioni) [inline src/LegacyPortal.js]: This seems to be unused

File: src/LegacyPortal.js [hunk 6]
```diff
@@ -0,0 +1,62 @@
+import React from 'react';
```
Comment (lencioni) [inline src/LegacyPortal.js]: It might be worth adding a comment at the top of this file explaining that this is used by React 15, or something like that.

File: src/LegacyPortal.js [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+import ReactDOM, { findDOMNode } from 'react-dom';
```
Comment (lencioni) [inline src/LegacyPortal.js]: findDOMNode seems to be unused

File: src/LegacyPortal.js [hunk 8]
```diff
@@ -0,0 +1,62 @@
...
+
+const KEYCODES = {
+  ESCAPE: 27
+};
+
+const canUseDOM = !!(
+  typeof window !== 'undefined' &&
+  window.document &&
+  window.document.createElement
+);
```
Comment (lencioni) [inline src/LegacyPortal.js]: It looks like this is duplicated from Portal. It seems like it should be moved to a module that both can share, or outsourced to a dependency that multiple packages can share.

File: src/LegacyPortal.js [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+      document.body.removeChild(this.props.node);
+    }
+    if (this.defaultNode) {
+      document.body.removeChild(this.defaultNode);
+    }
+    this.defaultNode = null;
+    this.portal = null;
+  }
+
+  renderPortal(props) {
```
Comment (lencioni) [inline src/LegacyPortal.js]: Why not put this in render instead of calling it manually from componentDidMount and componentWillReceiveProps?

Comment (brucewpaul) [reply src/LegacyPortal.js]: calling it in render was giving warnings: `Warning: _renderNewRootComponent(): Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate. Check the render method of Portal.`

File: src/LegacyPortal.js [hunk 10]
```diff
@@ -0,0 +1,56 @@
+// This file is a fallback for a consumer who is not yet on React 16
+// as createPortal was introduced in React 16
+
+import React from 'react';
+import ReactDOM from 'react-dom';
+import PropTypes from 'prop-types';
+import { canUseDOM } from './utils';
```
Comment (tajo) [inline src/LegacyPortal.js]: This is not used?

Comment (brucewpaul) [reply src/LegacyPortal.js]: ya, seems like it now that `renderPortal` is not being called in render

**Comment by brucewpaul** [comment]
We just tested this with react-dates and it appears to be working on 15.6 and 16

**Comment by brucewpaul** [comment]
@tajo let me know things are looking good and I can squash these commits

File: package.json [hunk 11]
```diff
@@ -66,8 +66,8 @@
     "jest": "^21.2.1",
     "prettier": "^1.5.3",
     "raf": "^3.4.0",
-    "react": "^15.0.0 || ^16.0.0",
-    "react-dom": "^15.0.0 || ^16.0.0",
+    "react": "^15.0.0 || ^16.0.0 || ^17.0.0",
+    "react-dom": "^15.0.0 || ^16.0.0 || ^17.0.0",
```
Comment (ljharb) [inline package.json]: these should all have `-0`, to match the peer dep

**Comment by brucewpaul** [comment]
cleaned up commits.

@tajo have you had a change to test it out on your end yet?

**Comment by tajo** [comment]
@brucewpaul 

So, the `examples/` should be updated to make it work with React 15 (now it uses an array as children v16 feature). But even then, it's not working with `React@15.6.2` for some reason:

```
bundle.js:20 Uncaught TypeError: Object(...) is not a function
    at t.value (bundle.js:20)
    at p._renderValidatedComponentWithoutOwnerOrContext (bundle.js:20)
    at p._renderValidatedComponent (bundle.js:20)
    at performInitialMount (bundle.js:20)
    at p.mountComponent (bundle.js:20)
    at Object.mountComponent (bundle.js:6)
    at Object.updateChildren (bundle.js:20)
    at m._reconcilerUpdateChildren (bundle.js:20)
    at m._updateChildren (bundle.js:20)
    at m.updateChildren (bundle.js:20)
```

**Comment by brucewpaul** [comment]
@tajo updated the examples, although it appears the PortalWithState isn't work with outside clicks, but nothing was changed for PWS. I'll be able to take a look at it later on today/tomorrow.

File: src/PortalWithState.js [hunk 12]
```diff
@@ -73,7 +73,7 @@ class PortalWithState extends React.Component {
     if (!this.state.active) {
       return;
     }
-    const root = findDOMNode(this.portalNode);
+    const root = findDOMNode(this.portalNode.defaultNode);
```
Comment (brucewpaul) [inline src/PortalWithState.js]: @tajo not sure about this, but this was how I got it to work in react 15.6.2 (also still works in react16). Before, findDOMNode was returning `null` if we didn't pass it the defaultNode

Comment (brucewpaul) [reply src/PortalWithState.js]: actually with this, we don't need findDOMNode, we can just access it directly with `this.portalNode.defaultNode`

**Comment by tajo** [comment]
Great job! Thanks!

**Comment by brucewpaul** [comment]
Thanks for helping address the issue and quick turn around!
